### ISSUE TITLE
json: cannot unmarshal array into Go struct field endpointResponse.col_types of type int

### ISSUE THREAD

**Issue by RichardLindhout** [herenow/go-crate#13]
When we update our depencies we got this error.
json: cannot unmarshal array into Go struct field endpointResponse.col_types of type int

Has is something to do with this commit?
https://github.com/herenow/go-crate/commit/4680fdfe704b97aa6b1590425697b6a297a5c9cd

**Comment by RichardLindhout** [comment]
@rousemobi

**Comment by bkleef** [comment]
We run CrateDB 1.1.2.

**Comment by bkleef** [comment]
Looks like this is related to https://github.com/herenow/go-crate/pull/11.

**Comment by herenow** [comment]
I'm guessing you guys have a `Set` or `Array` column, right?

We weren't handling this column types, I expected crate to always return an array of integers as the column types, but when the column is an `Array` or `Set` the value may be a nested array.

**Comment by herenow** [comment]
I've merged a fix, tell me if it works.

**Comment by RichardLindhout** [comment]
Yes that's right! Thanks a lot.
